name: AI Assisted Docs CI

on:
  push:
    branches: [ main ]
    paths:
      - 'ai-assisted-docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ai-assisted-docs/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432 # Example: Expose PostgreSQL port if used by Supabase in docker-compose

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Docker Compose services
        run: |
          cd ai-assisted-docs
          docker-compose up -d

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd ai-assisted-docs
          npm install

      - name: Lint
        run: |
          cd ai-assisted-docs
          npm run lint

      - name: Build
        run: |
          cd ai-assisted-docs
          npm run build

      - name: Run Tests
        run: |
          cd ai-assisted-docs
          npm test

      - name: Stop Docker Compose services
        run: |
          cd ai-assisted-docs
          docker-compose down

